name: Publish to CocoaPods
on:
  release:
    types: [released, prereleased]
jobs:
  publish:
    name: Release build and publish
    runs-on: macOS-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod repo update
      - name: Define podspec path
        run: echo "PODSPEC_PATH=library/fibonacci.podspec" >> $GITHUB_ENV
      - name: Publish to CocoaPods Trunk
        run: pod trunk push $PODSPEC_PATH
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
