name: Publish to CocoaPods
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    name: Release build and publish
    runs-on: macOS-latest
    steps:
#      - name: Set up Ruby
#        uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: 3.1
#      - name: Install CocoaPods
#        run: |
#          gem install cocoapods
#          pod repo update
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Publish to MavenCentral
        run: ./gradlew podPublishXCFramework --stacktrace # | pod trunk push
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
          PATH: ${{ secrets.PODSPEC_PATH }}